export const products =[
    {
      id: "vin-moto-01",
      brand: "Vinfast",
      category: "Electric Vehicle",
      type: "Moto",
      name: "Vinfast Theon S",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dwb9c8d350/images/PDP-XMD/theons/img-banner-info.webp",
      description: "VinFast Theon S là mẫu xe máy điện với tốc độ tối đa 99 km/h, quãng đường di chuyển 150 km/lần sạc. Được trang bị động cơ 7100W, công nghệ pin LFP, cốp xe rộng 24 lít, và công nghệ PAAK hiện đại.",
      detail: "VinFast Theon S nổi bật với tốc độ tối đa 99 km/h và khả năng di chuyển lên tới 150 km/lần sạc. Động cơ điện trung tâm sản sinh công suất tối đa 7100W, truyền động bằng dây xích, cùng với công nghệ pin LFP vượt trội, giúp xe hoạt động an toàn và ổn định. An toàn được đảm bảo thông qua hệ thống phanh ABS 2 kênh Continental, chống trượt trong quá trình di chuyển. Công nghệ PAAK (Phone As A Key) cho phép điều khiển xe qua ứng dụng điện thoại, kết nối HMI tích hợp Esim, và khóa thông minh với cảm biến tự động. Cốp xe rộng tới 24 lít, hệ thống đèn Full LED và đèn pha projector tăng cường khả năng chiếu sáng. Công nghệ Pin LFP tăng công suất động cơ, tốc độ lớn nhất, và quãng đường di chuyển tối đa, giảm thiểu tiêu hao, ổn định và an toàn hơn. Thời gian sạc khoảng 6 giờ từ 0-100%, với cách bảo quản thông minh giúp duy trì dung lượng pin. VinFast Theon S không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, kết nối mọi hành trình, và đảm bảo trải nghiệm đỉnh cao cho người sử dụng.",
      price: "69900000",
      power: "7100",
      longevity: "7.5",
      Co2: "1959.0204081632653"
    },
    {
      id: "vin-moto-02",
     brand: "Vinfast",
      category: "Electric Vehicle",
      type: "Moto",
      name: "Vinfast Theon",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw3f26d5e6/images/theon/RES.webp",
      description: "VinFast Theon là một mẫu xe máy điện hiện đại với kiểu dáng thể thao, động cơ 3500W, tốc độ tối đa 90km/h. Xe được trang bị công nghệ PAAK, hệ thống phanh ABS, pin Lithium của Samsung, và nhiều tính năng an toàn và tiện ích khác.",
      detail: "VinFast Theon là một mẫu xe máy điện thể thao, mạnh mẽ, được thiết kế bởi đơn vị danh tiếng Kiska. Động cơ điện trung tâm 3500W, truyền động bằng dây xích, cho phép tốc độ tối đa 90km/h và tăng tốc từ 0-50km/h trong 6 giây. An toàn được đảm bảo bằng hệ thống phanh ABS Continental và tiêu chuẩn chống nước IP67. Xe được trang bị công nghệ PAAK (Phone As A Key) cho phép điều khiển xe qua App điện thoại, kết nối HMI tích hợp Esim cho việc tự động chuẩn đoán lỗi, cập nhật phần mềm, và định vị GPS. Khóa thông minh với cảm biến tự động khởi động và tắt máy cũng là một tính năng nổi bật. Pin Lithium sử dụng công nghệ Cell Pin của Samsung và công nghệ Pack Pin tiên tiến của VinFast, đạt chuẩn châu Âu UNR R136, cho phép quãng đường hoạt động lên đến 101km và sạc đầy trong 5.5 giờ. Hệ thống đèn Full LED, cốp xe rộng 17 lít, và hệ thống giảm xóc Showa của Nhật Bản cũng góp phần tạo nên trải nghiệm lái hoàn hảo. VinFast Theon không chỉ mạnh mẽ và thể thao mà còn thời thượng với các công nghệ bứt phá, kết nối mọi hành trình, và đảm bảo an toàn đẳng cấp, thách thức mọi giới hạn.",
      price: "63900000",
      power: "7100",
      longevity: "7.5",
      Co2: "1959.0204081632653"
    },
    {
      id: "vin-moto-03",
     brand: "Vinfast",
      category: "Electric Vehicle",
      type: "Moto",
      name: "Vinfast Vento S",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw9b5dac28/images/PDP-XMD/ventos/img-top-ventos-yellow.webp",
      description: "VinFast Vento S là mẫu xe máy điện với tốc độ tối đa 89 km/h, quãng đường di chuyển 160 km/lần sạc. Được trang bị động cơ Side Motor 5200W, công nghệ pin LFP, cốp xe rộng 25 lít, và công nghệ PAAK hiện đại.",
      detail: "VinFast Vento S đặc biệt với tốc độ tối đa 89 km/h và khả năng di chuyển lên tới 160 km/lần sạc. Động cơ Side Motor với công suất tối đa 5200W giúp xe vận hành tốt hơn, bền bỉ hơn và tiết kiệm năng lượng. Công nghệ pin LFP giúp xe đạt hiệu suất vận hành cao, an toàn và thân thiện môi trường. An toàn được đảm bảo thông qua phanh đĩa trước trang bị ABS, giảm xóc ống lồng và giảm chấn thủy lực. Công nghệ PAAK (Phone As A Key) cho phép điều khiển xe qua app điện thoại, kết nối HMI tích hợp Esim, và khóa thông minh với cảm biến tự động. Cốp xe rộng tới 25 lít, yên xe có chiều cao 780 mm được thiết kế lớp mút dày và bề mặt yên rộng rãi, tư thế ngồi lịch lãm và thoải mái. Sàn để chân rộng rãi và vị trí để chân sau tách rời giúp tư thế ngồi thư thái và thoải mái. Hệ thống đèn Full LED bao gồm cả đèn pha, đèn hậu, đèn xi nhan, đèn phanh, và đèn pha LED Projector nâng cao khả năng chiếu sáng mạnh mẽ, an toàn khi di chuyển vào ban đêm. VinFast Vento S không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, thách thức mọi giới hạn, và đảm bảo trải nghiệm đỉnh cao cho người sử dụng.",
      price: "56000000",
      power: "5200",
      longevity: "7.5",
      Co2: "1434.7755102040817"
    },
    {
      id: "vin-moto-04",
     brand: "Vinfast",
      category: "Electric Vehicle",
      type: "Moto",
      name: "Vinfast Vento",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw6ee5b103/images/vento/Xe-may-dien-VinFast-Vento-mau-xanh-yen-nau.webp",
     description: "VinFast Vento là mẫu xe máy điện với tốc độ tối đa 80 km/h, quãng đường di chuyển 110 km/lần sạc. Được trang bị động cơ IPM 4000W, công nghệ pin Lithium, cốp xe rộng 17 lít, và công nghệ PAAK hiện đại.",
     detail: "VinFast Vento đánh dấu sự bứt phá công nghệ với tốc độ tối đa 80 km/h và khả năng di chuyển lên tới 110 km/lần sạc. Động cơ IPM với công suất tối đa 4000W giúp xe vận hành tốt hơn, bền bỉ hơn và tiết kiệm năng lượng. Công nghệ pin Lithium ion hiệu năng vượt trội, sử dụng cell pin của Samsung và công nghệ sản xuất tiên tiến do VinFast nghiên cứu và phát triển. An toàn được đảm bảo thông qua phanh đĩa trang bị ABS Continental, tiêu chuẩn chống nước động cơ IP67. Công nghệ PAAK (Phone As A Key) cho phép điều khiển xe qua app điện thoại, kết nối HMI tích hợp Esim, và khóa thông minh với cảm biến tự động. Thiết kế thời thượng, kiêu hãnh cùng những gam màu trẻ trung phóng khoáng. Hệ thống đèn pha projector hình kim cương, đèn xi nhan dạng dynamic turn đẳng cấp. Cốp xe rộng tới 17 lít, yên xe có chiều cao 780 mm được thiết kế lớp mút dày và bề mặt yên rộng rãi, tư thế ngồi lịch lãm và thoải mái. Gầm xe được thiết kế cao 145 mm sẵn sàng vượt qua mọi cung đường gồ ghề và lên xuống vỉa hè trong phố. Hệ thống đèn Full LED bao gồm cả đèn pha, đèn hậu, đèn xi nhan, đèn phanh, và đèn pha LED Projector nâng cao khả năng chiếu sáng mạnh mẽ, an toàn khi di chuyển vào ban đêm. VinFast Vento không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, bứt phá công nghệ, tiên phong dẫn bước, và đảm bảo trải nghiệm đỉnh cao cho người sử dụng.",
      price: "56350000",
      power: "4000",
      longevity: "7.5",
      Co2: "1103.6734693877552"
    },
    {
     id: "vin-moto-05",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Moto",
      name: "Vinfast Feliz",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw4afac7d9/images/PDP-XMD/felizs/img-top-felizs-white-sp.webp",
     description: "VinFast Feliz S là mẫu xe máy điện với tốc độ tối đa 78 km/h, quãng đường di chuyển 198 km/lần sạc. Được trang bị động cơ 3000W, công nghệ pin LFP 3,5 KWh, cốp xe rộng 25 lít, và công nghệ chống nước IP67.",
     detail: "VinFast Feliz S đánh dấu sự tiến bộ với tốc độ tối đa 78 km/h và khả năng di chuyển lên tới 198 km/lần sạc. Động cơ điện được nâng cấp với công suất tối đa 3000W, cùng công nghệ pin LFP 3,5 KWh, cho quãng đường lên tới 198 km chỉ với 1 lần sạc. An toàn được đảm bảo thông qua hệ thống phanh đĩa trước và phanh cơ sau, bộ giảm xóc trước/sau giúp xe vận hành êm ái. Công nghệ chống nước IP67 hoạt động ổn định ngay cả khi ngập nước 0,5m trong 30 phút. Thiết kế thời trang, hiện đại, trẻ trung, phong cách, với các màu sắc như Xanh rêu, Đen bóng, Đỏ rượu vang, Trắng ngọc trai-đen, Bạc. Hệ thống đèn full LED và đèn pha Projector tiêu chuẩn ECE Châu Âu, cùng với vỏ xe 14 inch cho phép di chuyển trên nhiều địa hình. Công nghệ Pin LFP tăng công suất động cơ, tốc độ lớn nhất, và quãng đường di chuyển tối đa, giảm thiểu tiêu hao, ổn định và an toàn hơn. Thời gian sạc khoảng 6 giờ từ 0-100%, với cách bảo quản thông minh giúp duy trì dung lượng pin. Cốp xe rộng tới 25 lít, khoảng sáng gầm xe 135 mm, và hai chế độ lái Eco và Sport linh hoạt trên mọi địa hình, tối ưu chi phí vận hành so với xe máy xăng. VinFast Feliz S không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, tối ưu hóa trải nghiệm, và đảm bảo trải nghiệm thú vị trên mọi địa hình.",
      price: "29900000",
      power: "3000",
      longevity: "7.5",
      Co2: "827.7551020408164"
    },
    {
     id: "vin-moto-06",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Moto",
      name: "Vinfast Klara S 2022",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dwce891876/images/PDP-XMD/klaras/img-top-klaras-white-sp.webp",
     description: "VinFast Klara S (2022) là mẫu xe máy điện với tốc độ tối đa 78 km/h, quãng đường di chuyển 194 km/lần sạc. Được trang bị động cơ Inhub 3000W, công nghệ pin LFP 3,5 KWh, cốp xe rộng 23 lít, và tiêu chuẩn chống nước IP67.",
     detail: "VinFast Klara S (2022) nổi bật với tốc độ tối đa 78 km/h và khả năng di chuyển lên tới 194 km/lần sạc. Động cơ Inhub do VinFast phát triển, công suất tối đa 3000W, cùng công nghệ pin LFP 3,5 KWh, giúp xe hoạt động an toàn và thân thiện với môi trường. An toàn được đảm bảo thông qua hệ thống phanh đĩa trước/sau, ống lồng-giảm chấn thủy lực trước và giảm xóc đôi, giảm chấn thủy lực sau. Tiêu chuẩn chống nước IP67, động cơ chống nước vượt trội ở mức nước ngập sâu 0,5m trong 30 phút. Thiết kế thú vị, trẻ trung, với các màu sắc như Xanh lục, Xanh đậm-đen, Trắng ngọc trai-đen, Đen nhám, Đỏ đậm-đen. Hệ thống đèn full LED, đèn pha LED, cốp xe rộng 23 lít, chiều cao yên 760 mm, và khoảng sáng gầm 125mm, cho phép di chuyển trên nhiều địa hình. Công nghệ Pin LFP tăng công suất động cơ, tốc độ lớn nhất, và quãng đường di chuyển tối đa, giảm thiểu tiêu hao, ổn định và an toàn hơn. Thời gian sạc khoảng 6 giờ từ 0-100%, với cách bảo quản thông minh giúp duy trì dung lượng pin. VinFast Klara S (2022) không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, tối ưu hóa trải nghiệm, và đảm bảo trải nghiệm thú vị trên mọi địa hình. Bảo hành chính hãng 03 năm không giới hạn số Km, đảm bảo sự yên tâm cho người sử dụng.",
      price: "36900000",
      power: "3000",
      longevity: "7.5",
      Co2: "827.7551020408164"
    },
    {
     id: "vin-moto-07",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Moto",
      name: "Vinfast Evo200",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw91eed064/images/PDP-XMD/evo200/img-pin.png",
     description: "VinFast EVO200 là mẫu xe máy điện với tốc độ tối đa 70 km/h, quãng đường di chuyển 203 km/lần sạc. Được trang bị động cơ Inhub 1500W, công nghệ pin LFP 3,5 KWh, cốp xe rộng 22 lít, và tiêu chuẩn chống nước IP67.",
     detail: "VinFast EVO200 đánh dấu sự tiến bộ với tốc độ tối đa 70 km/h và khả năng di chuyển lên tới 203 km/lần sạc. Động cơ Inhub 1500W, công nghệ pin LFP 3,5 KWh, giúp xe hoạt động an toàn và ổn định, với thời gian sạc tiêu chuẩn khoảng 10h từ 0-100%. Thiết kế trang nhã và hài hòa, thanh thoát đầy tinh tế trong từng đường nét, với các màu sắc như Đỏ tươi, Trắng ngọc trai, Xanh tím than, Vàng, Đen Nhám. Hệ thống đèn Full LED và đèn pha projector, cốp xe rộng 22 lít, và giảm xóc ống lồng-giảm chấn thủy lực, giảm xóc đôi, giảm chấn thủy lực. Tiêu chuẩn chống nước IP67, động cơ có khả năng chống nước vượt trội ở mức nước ngập sâu 0,5m trong 30 phút. Công nghệ Pin LFP vượt trội với công nghệ pack pin và phần mềm quản lý do VinFast tự nghiên cứu & phát triển. Kích thước tầm trung phù hợp người Việt tạo cảm giác lái thoải mái, êm ái trên nhiều loại địa hình. Tăng tốc từ 0-50 km/h chỉ trong 14 giây, vận hành mãnh mẽ trên mọi địa hình. VinFast EVO200 không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, nối dài tự do, mở rộng trải nghiệm, và đảm bảo trải nghiệm thú vị trên mọi địa hình.",
      price: "22000000",
      power: "2500",
      longevity: "7.5",
      Co2: "689.795918367347"
    },
    {
     id: "vin-moto-08",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Moto",
      name: "Vinfast Evo200 Lite",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw442825b0/images/PDP-XMD/evo200-lite/img-banner-info.webp",
     description: "VinFast EVO200 Lite là mẫu xe máy điện với tốc độ tối đa 49 km/h, quãng đường di chuyển 205 km/lần sạc. Được trang bị động cơ Inhub 1500W, công nghệ pin LFP 3,5 KWh, cốp xe rộng 22 lít, và tiêu chuẩn chống nước IP67.",
     detail: "VinFast EVO200 Lite nổi bật với tốc độ tối đa 49 km/h và khả năng di chuyển lên tới 205 km/lần sạc. Động cơ Inhub 1500W, công nghệ pin LFP 3,5 KWh, giúp xe hoạt động an toàn và ổn định, với thời gian sạc tiêu chuẩn khoảng 10h từ 0-100%, hoặc 4h sạc nhanh. Thiết kế trẻ trung, hiện đại và đầy khác biệt, với các màu sắc như Đỏ tươi, Trắng ngọc trai, Xanh tím than, Vàng, Đen Nhám. Hệ thống đèn Full LED và đèn pha projector, cốp xe rộng 22 lít, và giảm xóc ống lồng-giảm chấn thủy lực, giảm xóc đôi, giảm chấn thủy lực. Tiêu chuẩn chống nước IP67, động cơ có khả năng chống nước vượt trội ở mức nước ngập sâu 0,5m trong 30 phút. Công nghệ Pin LFP vượt trội với công nghệ pack pin và phần mềm quản lý do VinFast tự nghiên cứu & phát triển. Kích thước tầm trung phù hợp với người Việt tạo cảm giác lái thoải mái, êm ái trên nhiều loại địa hình. Tăng tốc từ 0-45 km/h chỉ trong 14 giây, vận hành mãnh mẽ trên mọi địa hình. VinFast EVO200 Lite không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, nối dài tự do, mở rộng trải nghiệm, và đảm bảo trải nghiệm thú vị trên mọi địa hình.",
      price: "19400000",
      power: "2450",
      longevity: "7.5",
      Co2: "676"
    },
    {
     id: "vin-oto-01",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Oto",
      name: "Vinfast VF5 Plus",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dwf7907695/images/PDP/VF5/vf5-1.png",
     description: "VinFast VF 5 Plus là mẫu xe điện A-SUV, với quãng đường di chuyển hơn 300 km/lần sạc, công suất tối đa 134 Hp, mô men xoắn cực đại 135 Nm. Thiết kế hiện đại, độc đáo, trang bị công nghệ thông minh, vận hành mạnh mẽ, an toàn.",
     detail: "VinFast VF 5 Plus là mẫu xe điện A-SUV, với quãng đường di chuyển hơn 300 km/lần sạc, công suất tối đa 134 Hp, mô men xoắn cực đại 135 Nm. Thiết kế hiện đại, độc đáo, trẻ trung, và cá tính, với các tùy chọn phối màu độc đáo và thời thượng. Xe được trang bị đầy đủ công nghệ tiên tiến bậc nhất như giám sát hành trình cơ bản, cảnh báo giao thông phía sau, cảnh báo điểm mù, hỗ trợ đỗ xe phía sau, hỗ trợ phanh khẩn cấp. Tích hợp các ứng dụng, tiện ích thông minh như trợ lý ảo điều khiển bằng giọng nói, mua sắm trực tuyến trên xe, điều khiển các thiết bị smart home, giúp nâng tầm trải nghiệm và kiến tạo một phong cách sống đẳng cấp, văn minh, hiện đại. Kích thước xe là 3.967 x 1.723 x 1.578 mm, dung lượng pin khả dụng 37,23 Kwh, loại la-zăng hợp kim 17 inch, mức tiêu thụ nhiên liệu công khai 115 Wh/km, số ghế ngồi 5 ghế, thời gian nạp pin nhanh nhất (10%-70%) 30 phút, và 6 túi khí. VinFast VF 5 Plus không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, đảm bảo trải nghiệm thú vị và an toàn trên mọi địa hình.",
      price: "538000000",
      power: "100004",
      longevity: "10",
      Co2: "16242"
    },
    {
     id: "vin-oto-02",
     brand: "Vinfast",
     category: "Electric Vehicle",
     type: "Oto",
      name: "Vinfast VF e34",
      url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw261ff57f/images/PDP/vfe34/vfe34-preview.webp",
     description: "VinFast VF e34 là mẫu xe điện C-SUV với thiết kế tinh tế, thân thiện với người dùng. Công suất tối đa 147 hp, mô-men xoắn cực đại 242 Nm, quãng đường di chuyển 318.6 km/lần sạc đầy. Trang bị công nghệ thông minh hiện đại, hứa hẹn nâng tầm trải nghiệm.",
     detail: "VinFast VF e34, mẫu xe điện C-SUV, kết hợp thiết kế tinh tế, thân thiện với người dùng và loạt công nghệ thông minh hiện đại. Công suất tối đa 147 hp, mô-men xoắn cực đại 242 Nm, quãng đường di chuyển 318.6 km/lần sạc đầy, tạo nên sự linh hoạt trong vận hành. Ngoại thất hiện đại, thu hút mọi ánh nhìn, với ngôn ngữ thiết kế Cân bằng động giúp xe luôn nổi bật, hiện đại và hướng tới tương lai. Thiết kế tăng cường tính khí động học, ánh sáng toả ra từ logo VinFast tạo cảm giác phóng khoáng và sang trọng. Nội thất rộng rãi, tiện nghi và hiện đại, không gian thoáng đãng nhờ động cơ điện và hệ thống pin tinh giản đặt dưới sàn xe. Khoang lái được bố trí tối ưu, giúp trải nghiệm lái hiệu quả và an toàn hơn. Trải nghiệm chiếc xe điện hiện đại và thông minh vượt trội cùng loạt tính năng hỗ trợ người lái về an toàn, điều hướng - dẫn đường, dịch vụ thông minh cùng trợ lý ảo hỗ trợ tương tác tự nhiên bằng Tiếng Việt đa vùng miền. Hệ thống trợ lái nâng cao ứng dụng công nghệ và trang thiết bị hiện đại nhất, đem lại trải nghiệm lái thư thái, dễ dàng. VinFast cung cấp đa dạng giải pháp sạc để đáp ứng nhu cầu sử dụng của Khách hàng một cách thuận tiện nhất. VinFast VF e34 không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, đảm bảo trải nghiệm thú vị và an toàn trên mọi địa hình.",
      price: "690000000",
      power: "110000",
      longevity: "10",
      Co2: "17865"
    },
    {
     id: "vin-oto-03",
     brand: "Vinfast",
     category: "Electric Vehicle",
type: "Oto",
      name: "Vinfast VF8",
       url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw4d54f126/images/PDP/vf8/img-CE18.webp",
     description: "VinFast VF 8 là mẫu xe eSUV cỡ trung thời thượng, kết hợp công nghệ cao cấp và kỹ thuật sản xuất đặc biệt. Công suất tối đa 402 hp, thời gian tăng tốc từ 0 - 100 km/h dưới 5.5 giây, quãng đường di chuyển 400 km/lần sạc đầy. Thiết kế hiện đại, ấn tượng.",
     detail: "VinFast VF 8, mẫu xe eSUV cỡ trung thời thượng, đạt đến sự kết hợp hoàn hảo giữa chất lượng và giá trị thông qua công nghệ cao cấp và dịch vụ tận tâm. Công suất tối đa 402 hp, thời gian tăng tốc từ 0 - 100 km/h dưới 5.5 giây, quãng đường di chuyển 400 km/lần sạc đầy. Thiết kế hiện đại định hình bởi triết lý “Cân bằng động”, với những khối cong mềm mại chấm phá bởi các đường cắt sắc nét, tạo nên ấn tượng mạnh mẽ, mang đầy hơi thở của tương lai. Không gian nội thất tinh tế được thiết kế bởi studio danh tiếng Pininfarina, tích hợp loạt công nghệ tiên tiến. Hợp tác cùng những đối tác hàng đầu trên toàn cầu, VinFast áp dụng những công nghệ hiện đại với thiết kế tập trung vào con người, đem lại trải nghiệm Trợ lý ảo cùng loạt Dịch vụ thông minh tiên tiến, như kết nối mua sắm trực tuyến, điều khiển các thiết bị Smart Home, xem film/video, chơi trò chơi điện tử. Hệ thống trợ lái nâng cao ứng dụng công nghệ và trang thiết bị hiện đại nhất, đem lại trải nghiệm lái thư thái, dễ dàng. VinFast cung cấp đa dạng giải pháp sạc, quy hoạch Hệ thống trạm sạc phủ khắp 63/63 tỉnh thành và 100% cao tốc, quốc lộ huyết mạch, 150.000 cổng sạc cho ô tô và xe máy điện. VinFast VF 8 không chỉ mạnh mẽ và hiện đại mà còn thể hiện sự tiên tiến trong công nghệ, đảm bảo trải nghiệm thú vị và an toàn trên mọi địa hình.",
      price: "1237000000",
      power: "204000",
      longevity: "10",
      Co2: "23461"
    },
    {
     id: "vin-oto-04",
     brand: "Vinfast",
     category: "Electric Vehicle",
       type: "Oto",
      name: "Vinfast VF9",
       url: "https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dwa6fa7521/images/PDP/vf9/img-CE18.webp",
     description: "VinFast VF 9 là mẫu xe SUV 7 chỗ hạng sang, với công suất tối đa 402 hp, thời gian tăng tốc từ 0 - 100 km/h khoảng 7.5 giây, quãng đường di chuyển 423 km/lần sạc đầy. Thiết kế tinh tế, công nghệ tiên tiến, mang đến trải nghiệm đẳng cấp.",
     detail: "VinFast VF 9, mẫu xe SUV 7 chỗ hàng đầu của VinFast, kết hợp kiểu dáng tinh tế, công nghệ tiên tiến và sự tỉ mỉ trong từng chi tiết. Công suất tối đa 402 hp, thời gian tăng tốc từ 0 - 100 km/h khoảng 7.5 giây, quãng đường di chuyển 423 km/lần sạc đầy. Thiết kế tối giản mang hơi hướng tương lai, tinh tế từ studio danh tiếng Pininfarina, tạo ấn tượng và cuốn hút. Hợp tác cùng đối tác hàng đầu toàn cầu, VinFast áp dụng công nghệ hiện đại, tập trung vào con người, đem lại trải nghiệm Trợ lý ảo cùng loạt Dịch vụ thông minh tiên tiến. Hệ thống trợ lái nâng cao ứng dụng công nghệ và trang thiết bị hiện đại, đem lại trải nghiệm lái thư thái, dễ dàng. VinFast cung cấp đa dạng giải pháp sạc, phủ khắp 63/63 tỉnh thành và 100% cao tốc, quốc lộ huyết mạch, 150.000 cổng sạc cho ô tô và xe máy điện. Vóc dáng bề thế của một chiếc SUV cỡ lớn cùng thiết kế giúp tối ưu tính khí động học, đem lại những trải nghiệm đẳng cấp. Tích hợp điều khiển các thiết bị Smart Home, xem film/video, chơi trò chơi điện tử, kết nối mua sắm trực tuyến. VinFast VF 9 không chỉ mạnh mẽ và bề thế mà còn thể hiện sự tiên tiến trong công nghệ, nâng tầm thời thượng, đảm bảo trải nghiệm đặc biệt cao cấp.",
      price: "1330560000",
      power: "300000",
      longevity: "10",
      Co2: "30680"
    },
    {
      id: "ca-solar-01",
      brand: "Canadian",
      category: "Recycled Energy",
     type: "Solar",
     name: "Solar System 5Kw",
      url: "https://sunemit.com/wp-content/uploads/2020/09/dien-mat-troi-5kW.jpg",
      description: "Hệ thống điện năng lượng mặt trời hòa lưới 5kWp bởi nó phù hợp với các thiết bị điện của hộ gia đình, sử dụng năng lượng sạch góp phần bảo vệ môi trường, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động.",
     detail: "Điện mặt trời mang lại nhiều lợi ích cả về kinh tế và môi trường sống cho người sử dụng. Vì vậy, ngày càng có nhiều gia đình và doanh nghiệp có nhu cầu lắp đặt điện năng lượng mặt trời hơn. Hệ thống pin năng lượng mặt trời 5kw được coi là kích cỡ hệ thống phù hợp với mức tiêu thụ điện năng của đa số các hộ gia đình. Hệ thống cung cấp lượng điện năng cần thiết cho các thiết bị trong nhà, sử dụng năng lượng sạch góp phần bảo vệ môi trường,thay mái chống nóng, chống ồn, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động. Đây có thể coi là hệ thống điện mặt trời hòa lưới được nhiều hộ gia đình lựa chọn nhất hiện nay. Với công suất và mức chi phí phù hợp, việc lắp đặt hệ thống năng lượng mặt trời hòa lưới 5kWp là giải pháp đúng đắn, an toàn và tiết kiệm cho các hộ gia đình hiện nay. ",
     price: "80000000",
     power: "5000",
     longevity: "12",
      Co2: "34339"
    },
    {
      id: "ca-solar-02",
      brand: "Canadian",
      category: "Recycled Energy",
     type: "Solar",
     name: "Solar System 10Kw",
      url: "https://sunemit.com/wp-content/uploads/2021/05/he-thong-nang-luong-mat-troi-tron-goi-10kw-e1621657603491.jpg",
      description: "Hệ thống điện năng lượng mặt trời hòa lưới 10kWp bởi nó phù hợp với các thiết bị điện của hộ gia đình, sử dụng năng lượng sạch góp phần bảo vệ môi trường, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động.",
     detail: "Điện mặt trời mang lại nhiều lợi ích cả về kinh tế và môi trường sống cho người sử dụng. Vì vậy, ngày càng có nhiều gia đình và doanh nghiệp có nhu cầu lắp đặt điện năng lượng mặt trời hơn. Hệ thống pin năng lượng mặt trời 10kw được coi là kích cỡ hệ thống phù hợp với mức tiêu thụ điện năng của đa số các hộ gia đình. Hệ thống cung cấp lượng điện năng cần thiết cho các thiết bị trong nhà, sử dụng năng lượng sạch góp phần bảo vệ môi trường,thay mái chống nóng, chống ồn, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động. Đây có thể coi là hệ thống điện mặt trời hòa lưới được nhiều hộ gia đình lựa chọn nhất hiện nay. Với công suất và mức chi phí phù hợp, việc lắp đặt hệ thống năng lượng mặt trời hòa lưới 10kWp là giải pháp đúng đắn, an toàn và tiết kiệm cho các hộ gia đình hiện nay. ",
     price: "150000000",
     power: "10000",
longevity: "12",
      Co2: "68678"
    },
    {
      id: "ca-solar-03",
      brand: "Canadian",
      category: "Recycled Energy",
     type: "Solar",
     name: "Solar System 20Kw",
      url: "https://sunemit.com/wp-content/uploads/2020/03/z2060021225050_aeddf6a8604099fb9a13a2d7766580bc.jpg",
      description: "Hệ thống điện năng lượng mặt trời hòa lưới 20kWp bởi nó phù hợp với các thiết bị điện của hộ gia đình, sử dụng năng lượng sạch góp phần bảo vệ môi trường, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động.",
     detail: "Điện mặt trời mang lại nhiều lợi ích cả về kinh tế và môi trường sống cho người sử dụng. Vì vậy, ngày càng có nhiều gia đình và doanh nghiệp có nhu cầu lắp đặt điện năng lượng mặt trời hơn. Hệ thống pin năng lượng mặt trời 20kw được coi là kích cỡ hệ thống phù hợp với mức tiêu thụ điện năng của đa số các hộ gia đình. Hệ thống cung cấp lượng điện năng cần thiết cho các thiết bị trong nhà, sử dụng năng lượng sạch góp phần bảo vệ môi trường,thay mái chống nóng, chống ồn, giúp tiết kiệm lượng điện năng tiêu thụ hàng ngày, tạo nguồn thu nhập thụ động. Đây có thể coi là hệ thống điện mặt trời hòa lưới được nhiều hộ gia đình lựa chọn nhất hiện nay. Với công suất và mức chi phí phù hợp, việc lắp đặt hệ thống năng lượng mặt trời hòa lưới 20kWp là giải pháp đúng đắn, an toàn và tiết kiệm cho các hộ gia đình hiện nay. ",
     price: "280000000",
     power: "20000",
longevity: "12",
      Co2: "137357"
    },
    {
      id: "dhc-wind-01",
      brand: "DHC",
      category: "Recycled Energy",
     type: "Wind",
     name: "Wind Turbine 3Kw",
      url: "https://www.dhcsolar.com/wp-content/uploads/2022/05/tuabin-dien-gio-3kw.jpg",
      description: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 10kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 10kW cao cấp.",
     detail: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 10kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 10kW cao cấp.",
     price: "46000000",
     power: "3000",
longevity: "15",
      Co2: "15453"
    },
    {
      id: "dhc-wind-02",
      brand: "DHC",
      category: "Recycled Energy",
     type: "Wind",
     name: "Wind Turbine 5Kw",
      url: "https://www.dhcsolar.com/wp-content/uploads/2022/04/tuabin-gio-5kw.jpg",
      description: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 5kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 5kW cao cấp.",
     detail: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 5kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 5kW cao cấp.",
     price: "130000000",
     power: "5000",
longevity: "15",
      Co2: "25754"
    },
    {
      id: "dhc-wind-03",
      brand: "DHC",
      category: "Recycled Energy",
     type: "Wind",
     name: "Wind Turbine 10Kw",
      url: "https://www.dhcsolar.com/wp-content/uploads/2022/04/tuabin-gio-10kW.jpg",
      description: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 10kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 10kW cao cấp.",
     detail: "Trước mắt các nguồn năng lượng hóa thạch đang dần cạn kiệt, gây ô nhiễm môi trường thì năng lượng tái tạo như điện gió và điện mặt trời đang rất yêu chuộng. Tài nguyên vô tận, sạch, có sẵn không mất phí, là những gì mà các năng lượng tái tạo có được. Ứng dụng năng lượng gió với Tuabin gió – giải pháp cấp điện cho hộ gia đình mang lại nhiều ưu điểm vượt trội. DHC muốn giới thiệu đến khách hàng tuabin gió 10kW, công suất cực lớn cho những hộ gia đình khó tiếp cận nguồn điện. Tuabin Điện gió 10kW cao cấp.",
     price: "190000000",
     power: "10000",
longevity: "15",
      Co2: "51509"
    }
  ]